config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'category/show/:id', to: 'categories#show', as: 'category'

  resources :courses
  resources :publications, only: [:index]

  root 'courses#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.employer?
      can :manage, [Category, Contact, Course, Teacher]
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :courses

  validates :name, {
    presence: true,
    uniqueness: true,
    length: { minimum: 3, maximum: 50 }
  }

  field :name, type: String
end

app/models/contact.rb
class Contact
  include Mongoid::Document

  embedded_in :course

  validates :first_name, :last_name, :phone, :email, presence: true

  field :first_name, type: String
  field :last_name, type: String
  field :phone, type: String
  field :facebook, type: String
  field :email, type: String
  field :skype, type: String
end

app/models/course.rb
class Course
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :contacts
  embeds_many :teachers

  belongs_to :category
  belongs_to :user

  validates :name, :description, :start_date, presence: true
  validates :name, length: { minimum: 5, maximum: 100 }
  validates :description, length: { minimum: 20, maximum: 500 }

  before_create :set_status

  field :name,          type: String
  field :description,   type: String
  field :start_date,    type: Date
  field :started,       type: Mongoid::Boolean, default: true
  field :confirmed,     type: Mongoid::Boolean

  scope :not_started, -> { where(started: false).and(confirmed: true) }

  def self.change_status
    all.each do |course|
      course.update_attribute(:started, true) if course.start_date < Date.today
    end
  end

  def set_status
    self.started = false if self.start_date >= Date.today
  end
end

app/models/teacher.rb
class Teacher
  include Mongoid::Document

  embedded_in :course

  field :first_name, type: String
  field :last_name, type: String
  field :age, type: Integer
  field :information, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include SimpleEnum::Mongoid

  attr_accessor :login

  has_many :courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :name,               type: String
  field :username,           type: String
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  as_enum :role, admin: 'Admin', user: 'User', employer: 'Employer'

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def self.find_for_database_authentication conditions
    login = conditions.delete(:login)
    any_of({username: login}, email: login).first
  end

  def self.delete_unconfirmed_user
    each do |user|
      user.delete if (user.created_at.strftime('%d-%m-%y') == (Date.today - 7).strftime('%d-%m-%y')) && (user.confirmed_at == nil)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @courses = @category.courses.not_started.order_by(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @courses = @category.courses.not_started.page(params[:page]).per(10)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, :set_categories, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.not_started.order_by(created_at: :desc).page(params[:page]).per(10)
  end

  def show; end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    puts params[:name]

    if @course.save!
      redirect_to publications_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @course.update_attributes(course_params)
      redirect_to publications_url
    else
      render 'edit'
    end
  end

  def destroy
    if @course.delete
      redirect_to publications_url
    else
      render 'index'
    end
  end

  private

  def set_categories
    @categories = Category.all
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :start_date, :category_id).merge(user_id: current_user.id, confirmed: true)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
    @courses = Course.where(user_id: current_user.id).order_by(created_at: :desc).page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories
    Category.all
  end
end

app/helpers/category_helper.rb
module CategoryHelper
  def categories
    Category.all
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def days_to_start(course)
    (course.start_date - Date.today).to_i
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/categories/show.html.haml
%h1
  = @category.name
%h1 Courses
%p
  .courses
    - @courses.each do |course|
      = link_to course_url(course) do
        %p
          .days_to_start
            Days to start:
            = days_to_start(course)
          .name
            Name:
            = course.name
          .description
            Description:
            = course.description.truncate(50)
          .start-date
            Start date:
            = course.start_date
= paginate @courses

app/views/courses/_form.html.haml
= form_for @course do |f|
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :description
    %br/
    = f.text_area :description
  %p
    = f.label :start_date
    %br/
    = f.text_field :start_date
  %p
    = f.collection_select :category_id, @categories, :_id, :name
  %p
    = f.submit

app/views/courses/edit.html.haml
%h1 Edit course
%p
  = render 'form'

app/views/courses/index.html.haml
%h1 Courses
%p
  - if can? :create, Course
    .add-new-course
      = link_to 'Create', new_course_url
  .courses
    - @courses.each do |course|
      %p
        .days_to_start
          Days to start:
          = days_to_start(course)
        .name
          Name:
          = course.name
        .category
          Category
          = course.category.name
        .description
          Description:
          = course.description.truncate(50)
        .start-date
          Start date:
          = course.start_date
        %div
          = link_to 'Read more...', course_url(course.id)
= paginate @courses

app/views/courses/new.html.haml
%h1 Create Course
%p
  = render 'form'

app/views/courses/show.html.haml
%h1
  Course:
  = @course.name
.days_to_start
  Days to start:
  = days_to_start(@course)
.category
  Category
  = @course.category.name
.description
  Description:
  = @course.description
.start-date
  Start date:
  = @course.start_date
%h1 Contacts
- @course.contacts.each do |contact|
  %p
    .name
      Name:
      = "#{contact.first_name} #{contact.last_name}"
    .phone
      Phone:
      = contact.phone
    .email
      Email:
      = contact.email
    .facebook
      = "Facebook: #{contact.facebook}" if contact.facebook
    .skype
      = "Skype: #{contact.skype}" if contact.skype
%h1 Teachers
- @course.teachers.each do |teacher|
  %p
    .name
      Name:
      = "#{teacher.first_name} #{teacher.last_name}"
    .age
      Age:
      = teacher.age
    .information
      = teacher.information

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CourseProject
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = link_to current_user.username, edit_user_registration_url
      = link_to 'Sign Out', destroy_user_session_url, method: :delete
    - if !user_signed_in?
      = link_to 'Sign In', new_user_session_url
      = link_to 'Sign Up', new_user_registration_url
    = render 'partials/header'
    = yield

app/views/partials/_header.html.haml
%p
  .menu
    = link_to 'Home', root_url
    - if user_signed_in?
      = link_to 'My Publications', publications_url
  .categories
    - categories.each do |category|
      |
      = link_to category.name, category_url(category.id)
    |

app/views/publications/index.html.haml
%h1 My Publications
.courses
  - @courses.each do |course|
    %p
      .days_to_start
        Days to start:
        = days_to_start(course)
      .name
        Name:
        = course.name
      .category
        Category
        = course.category.name
      .description
        Description:
        = course.description.truncate(50)
      .start-date
        Start date:
        = course.start_date
      %div
        = link_to 'Show', course_url(course.id)
        %br/
        = link_to 'Edit', edit_course_url(course.id)
        %br/
        = link_to 'Delete', course_url(course.id), method: :delete
= paginate @courses